"""N76 live-writer.

Runs the N76 write plan generated by mapper.build_plan() against a live
radio via benlink, with a full backup of all 5 regions before writing.

Usage:
    python -m radio_configs.targets.n76.writer --radio n76-vero --dry-run
    python -m radio_configs.targets.n76.writer --radio n76-vero --apply
    python -m radio_configs.targets.n76.writer --radio n76-vero --rollback
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
from pathlib import Path

from radio_configs.models import load_groups, load_radios
from radio_configs.resolver import resolve_layout
from radio_configs.targets.n76.mapper import (
    N76ChannelPlan,
    N76WritePlan,
    build_plan,
    format_plan,
)

ROOT = Path(__file__).resolve().parents[4]  # repo root
BACKUPS_ROOT = ROOT / "backups"


# ---------------------------------------------------------------------------
# Serialization for backup files
# ---------------------------------------------------------------------------

def _channel_to_dict(ch) -> dict:
    """benlink.command.Channel → JSON-safe dict."""
    d = ch.model_dump()
    for k in ("tx_sub_audio", "rx_sub_audio"):
        v = d.get(k)
        if hasattr(v, "n"):
            d[k] = {"__dcs__": v.n}
    return d


def _dict_to_channel(d: dict):
    from benlink.command import DCS, Channel
    d = dict(d)
    for k in ("tx_sub_audio", "rx_sub_audio"):
        v = d.get(k)
        if isinstance(v, dict) and "__dcs__" in v:
            d[k] = DCS(n=v["__dcs__"])
    return Channel(**d)


# ---------------------------------------------------------------------------
# Plan → benlink Channel
# ---------------------------------------------------------------------------

def _channel_from_plan(cp: N76ChannelPlan):
    """N76ChannelPlan → benlink.command.Channel."""
    from benlink.command import DCS, Channel

    def _sub_audio(v):
        if v is None:
            return None
        if isinstance(v, tuple) and v[0] == "D":
            return DCS(n=int(v[1]))
        return float(v)

    return Channel(
        channel_id=cp.channel_id,
        tx_mod="FM",
        tx_freq=cp.tx_freq,
        rx_mod="FM",
        rx_freq=cp.rx_freq,
        tx_sub_audio=_sub_audio(cp.tx_sub_audio),
        rx_sub_audio=_sub_audio(cp.rx_sub_audio),
        scan=cp.scan,
        tx_at_max_power=True,
        talk_around=False,
        bandwidth=cp.bandwidth,
        pre_de_emph_bypass=False,
        sign=False,
        tx_at_med_power=False,
        tx_disable=cp.tx_disable,
        fixed_freq=False,
        fixed_bandwidth=False,
        fixed_tx_power=False,
        mute=cp.mute,
        name=cp.name,
    )


def _blank_channel(slot_idx0: int):
    from benlink.command import Channel
    return Channel(
        channel_id=slot_idx0,
        tx_mod="FM",
        tx_freq=0.0,
        rx_mod="FM",
        rx_freq=0.0,
        tx_sub_audio=None,
        rx_sub_audio=None,
        scan=False,
        tx_at_max_power=True,
        talk_around=False,
        bandwidth="WIDE",
        pre_de_emph_bypass=False,
        sign=False,
        tx_at_med_power=False,
        tx_disable=False,
        fixed_freq=False,
        fixed_bandwidth=False,
        fixed_tx_power=False,
        mute=False,
        name="",
    )


# ---------------------------------------------------------------------------
# Radio interaction
# ---------------------------------------------------------------------------

async def _find_radio(preferred_addr: str = "", timeout: float = 12.0) -> str:
    """Scan for the N76, matching by name or preferred BLE address."""
    from bleak import BleakScanner

    print(f"scanning {timeout}s for VR-N76...")
    devices = await BleakScanner.discover(timeout=timeout)
    if preferred_addr:
        for d in devices:
            if d.address.upper() == preferred_addr.upper():
                print(f"  matched preferred address {d.address}")
                return d.address
    for d in devices:
        if d.name and "VR-N76" in d.name.upper():
            print(f"  matched by name {d.name!r} @ {d.address}")
            return d.address
    raise RuntimeError("N76 not found")


async def _read_all_regions(radio) -> dict[int, dict[int, dict]]:
    """Snapshot every channel of every region."""
    saved = radio.status.curr_region
    snap: dict[int, dict[int, dict]] = {}
    for r_idx in range(len(radio.region_names)):
        if r_idx != radio.status.curr_region:
            await radio.set_region(r_idx)
        region_snap: dict[int, dict] = {}
        for i in range(radio.device_info.channel_count):
            region_snap[i] = _channel_to_dict(radio.channels[i])
        snap[r_idx] = region_snap
        print(f"  backed up region {r_idx} "
              f"({radio.region_names[r_idx]!r}): {len(region_snap)} slots")
    if radio.status.curr_region != saved:
        await radio.set_region(saved)
    return snap


def _backup_dir(radio_id: str) -> Path:
    p = BACKUPS_ROOT / radio_id
    p.mkdir(parents=True, exist_ok=True)
    return p


def _save_backup(radio_id: str, snap: dict, region_names: list[str]) -> Path:
    ts = time.strftime("%Y%m%d-%H%M%S")
    path = _backup_dir(radio_id) / f"n76-full-backup-{ts}.json"
    payload = {
        "timestamp": ts,
        "radio_id": radio_id,
        "region_names": region_names,
        "regions": {str(r): {str(c): v for c, v in ch.items()} for r, ch in snap.items()},
    }
    path.write_text(json.dumps(payload, indent=2))
    print(f"  backup saved → {path.relative_to(ROOT)}")
    return path


def _latest_backup(radio_id: str) -> Path | None:
    files = sorted(_backup_dir(radio_id).glob("n76-full-backup-*.json"))
    return files[-1] if files else None


async def _apply_plan(radio, plan: N76WritePlan) -> None:
    conn = radio._conn

    print("\n--- region renames ---")
    for rid, name in plan.region_renames.items():
        await radio.set_region_name(rid, name)
        print(f"  region {rid} → {name!r}")

    for region in plan.regions:
        print(f"\n--- writing region {region.region_id} ({region.name!r}) ---")
        for cp in region.channels:
            ch = _channel_from_plan(cp)
            await conn.write_region_channel(region.region_id, ch)
        if region.channels:
            print(f"  wrote {len(region.channels)} filled slots")
        for slot0 in region.blank_slots:
            ch = _blank_channel(slot0)
            await conn.write_region_channel(region.region_id, ch)
        if region.blank_slots:
            print(f"  blanked {len(region.blank_slots)} slots "
                  f"({region.blank_slots[0]+1}..{region.blank_slots[-1]+1})")


async def _rollback(radio, backup_path: Path) -> None:
    data = json.loads(backup_path.read_text())
    conn = radio._conn

    print("\n--- restore region names ---")
    for rid, name in enumerate(data["region_names"]):
        try:
            await radio.set_region_name(rid, name)
            print(f"  region {rid} → {name!r}")
        except Exception as e:
            print(f"  region {rid} restore FAILED: {e!r}")

    print("\n--- restore channels ---")
    for r_str, chans in data["regions"].items():
        rid = int(r_str)
        for _c_str, cdict in chans.items():
            ch = _dict_to_channel(cdict)
            await conn.write_region_channel(rid, ch)
        print(f"  region {rid}: {len(chans)} slots restored")

    print("\nrollback complete.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _load_radio_and_plan(radio_id: str):
    groups = load_groups(ROOT / "groups")
    radios = load_radios(ROOT / "radios")
    if radio_id not in radios:
        raise SystemExit(f"unknown radio {radio_id!r}")
    radio_cfg = radios[radio_id]
    if radio_cfg.target != "n76":
        raise SystemExit(f"radio {radio_id!r} is not an n76 target (target={radio_cfg.target})")
    layout = resolve_layout(radio_cfg, groups)
    plan = build_plan(layout, channels_per_region=radio_cfg.capacity.channels_per_container)
    return radio_cfg, plan


async def _main_async(args: argparse.Namespace) -> None:
    radio_cfg, plan = _load_radio_and_plan(args.radio)

    if args.dry_run:
        print(format_plan(plan))
        return

    address = await _find_radio(radio_cfg.ble_address)
    print(f"connecting to {address}...")

    import benlink.controller as bc

    async with bc.RadioController.new_ble(address) as radio:
        print(f"connected fw={radio.device_info.firmware_version}")
        print(f"current region: {radio.status.curr_region}")
        print(f"region names: {radio.region_names}\n")

        if args.rollback:
            bpath = _latest_backup(radio_cfg.id)
            if not bpath:
                print("no backup found. aborting.")
                return
            print(f"restoring from {bpath.relative_to(ROOT)}...")
            await _rollback(radio, bpath)
            return

        # --apply
        print("=== plan ===")
        print(format_plan(plan))

        print("\n=== BACKING UP (all regions) ===")
        snap = await _read_all_regions(radio)
        _save_backup(radio_cfg.id, snap, list(radio.region_names))

        print("\n=== APPLYING WRITES ===")
        await _apply_plan(radio, plan)

        print("\ndone.")


def main() -> None:
    ap = argparse.ArgumentParser(description="N76 writer for radio_configs")
    ap.add_argument("--radio", required=True, help="radio id in radios/*.yml")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--dry-run", action="store_true")
    g.add_argument("--apply", action="store_true")
    g.add_argument("--rollback", action="store_true")
    args = ap.parse_args()
    asyncio.run(_main_async(args))


if __name__ == "__main__":
    main()
